# Generated by Django 4.2.16 on 2024-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vn', 'Vietnamese')], default='en', help_text='Choose the language that the book is written in', max_length=2),
        ),
    ]
